"""
WORKFLOW: Portfolio Monitor
---------------------------
INPUT:   List of portfolio companies (or empty to scan knowledge base)
CONTEXT: Existing company briefs from knowledge base
PROCESS: Exa pulls recent news, Claude flags what needs attention — structured output
OUTPUT:  Weekly digest saved to knowledge_base/meetings/
"""

import os
import sys
import requests
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel

sys.path.append(str(Path(__file__).parent.parent.parent))
from core.engine import call_claude_structured, load_context, save_output, KB


# ── Pydantic schema ────────────────────────────────────────────────────────────

class CompanyUpdate(BaseModel):
    company: str
    status: str          # "Action Required" | "Worth Noting" | "No Update"
    summary: str         # 1-2 sentences


class PortfolioDigest(BaseModel):
    week_summary: str              # 2-3 sentence overview
    updates: list[CompanyUpdate]
    priority_company: str          # name of the one to focus on this week
    priority_reason: str           # one sentence why


# ── Company list from knowledge base ──────────────────────────────────────────

def get_portfolio_companies() -> list[str]:
    companies_dir = KB / "companies"
    if not companies_dir.exists():
        return []
    names = []
    for f in companies_dir.glob("*.md"):
        parts = f.stem.split("_")
        if parts and parts[-1].isdigit() and len(parts[-1]) == 8:
            parts = parts[:-1]
        names.append(" ".join(p.capitalize() for p in parts))
    return names


# ── News fetch ─────────────────────────────────────────────────────────────────

def quick_news(company: str) -> str:
    api_key = os.getenv("EXA_API_KEY")
    if not api_key:
        return "No live data — add EXA_API_KEY to .env"
    try:
        response = requests.post(
            "https://api.exa.ai/search",
            headers={"x-api-key": api_key, "Content-Type": "application/json"},
            json={
                "query": f"{company} news funding announcement 2025 2026",
                "numResults": 3,
                "contents": {"text": {"maxCharacters": 400}},
            },
            timeout=10,
        )
        results = response.json().get("results", [])
        if not results:
            return "No recent news found."
        return "\n".join(f"- {r.get('title','')} ({r.get('url','')})" for r in results)
    except Exception:
        return "Search unavailable."


# ── Main workflow ──────────────────────────────────────────────────────────────

def portfolio_digest(companies: list[str] = None) -> dict:
    """
    Generate a weekly portfolio digest.
    Returns dict with digest (markdown), companies_monitored, file_path.
    """

    # STEP 1: CONTEXT
    if not companies:
        companies = get_portfolio_companies()
    if not companies:
        return {
            "status": "no_companies",
            "message": "No companies found. Add company briefs first via Company Research.",
            "digest": "",
            "companies_monitored": 0,
            "file_path": "",
        }

    # STEP 2: INPUT — news per company (cap at 10 to avoid rate limits)
    updates_text = ""
    for company in companies[:10]:
        updates_text += f"\n### {company}\n{quick_news(company)}\n"

    # STEP 3: PROCESS
    system = """You are a portfolio monitoring assistant for a VC investor.
Produce a concise weekly digest that flags what actually needs attention.

Rules:
- Prioritise by urgency: "Action Required" > "Worth Noting" > "No Update"
- Be honest about companies with no notable updates
- Flag companies with significant news (fundraising, pivots, leadership changes)
- priority_company is the single most important company to focus on this week"""

    user = f"""Here are the latest signals for portfolio companies.
Produce a weekly digest.

{updates_text}

Date: {datetime.now().strftime('%d %B %Y')}"""

    digest_data = call_claude_structured(system, user, schema=PortfolioDigest, max_tokens=1000)

    # STEP 4: OUTPUT — render to markdown and save
    updates_md = ""
    for u in digest_data.updates:
        icon = {"Action Required": "🔴", "Worth Noting": "🟡", "No Update": "⚪"}.get(u.status, "⚪")
        updates_md += f"### {icon} {u.company} — {u.status}\n{u.summary}\n\n"

    date_str = datetime.now().strftime("%d %B %Y")
    md = f"""# Portfolio Digest — {date_str}

{digest_data.week_summary}

---

{updates_md}
## This Week's Priority: {digest_data.priority_company}
{digest_data.priority_reason}

---
*Generated by AI-OS · {date_str}*"""

    filename  = f"portfolio_digest_{datetime.now().strftime('%Y%m%d')}.md"
    file_path = save_output(md, "meetings", filename)

    return {
        "companies_monitored": len(companies),
        "digest":              md,
        "file_path":           str(file_path),
        "priority_company":    digest_data.priority_company,
    }
