"""
WORKFLOW: Company Research
--------------------------
INPUT:   Company name (+ optional sector hint)
CONTEXT: Investment thesis from knowledge base
PROCESS: Exa pulls live signals, Claude analyses against thesis — structured output
OUTPUT:  Structured one-page brief saved to knowledge_base/companies/
"""

import os
import sys
import requests
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel

sys.path.append(str(Path(__file__).parent.parent.parent))
from core.engine import call_claude_structured, load_context, save_output


# ── Pydantic schema ────────────────────────────────────────────────────────────

class CompanyBrief(BaseModel):
    sector: str
    stage: str
    geography: str
    what_they_do: str
    funding_history: str
    team: str
    traction_signals: str
    red_flags: str
    thesis_fit: str          # "Strong" | "Partial" | "Weak"
    thesis_fit_reason: str
    recommended_next_step: str


# ── Exa search ─────────────────────────────────────────────────────────────────

def exa_search(query: str, num_results: int = 5) -> list[dict]:
    api_key = os.getenv("EXA_API_KEY")
    if not api_key:
        return [{"title": "Exa not configured", "url": "", "text": "Add EXA_API_KEY to .env to enable live research."}]
    try:
        response = requests.post(
            "https://api.exa.ai/search",
            headers={"x-api-key": api_key, "Content-Type": "application/json"},
            json={
                "query": query,
                "numResults": num_results,
                "contents": {"text": {"maxCharacters": 800}},
            },
            timeout=15,
        )
        return [
            {"title": r.get("title", ""), "url": r.get("url", ""), "text": r.get("text", "")}
            for r in response.json().get("results", [])
        ]
    except Exception as e:
        return [{"title": "Search error", "url": "", "text": str(e)}]


def _format_signals(results: list[dict]) -> str:
    lines = []
    for i, r in enumerate(results, 1):
        lines.append(f"**Source {i}: {r['title']}**")
        if r.get("url"):
            lines.append(f"URL: {r['url']}")
        lines.append(r.get("text", ""))
        lines.append("")
    return "\n".join(lines)


# ── Main workflow ──────────────────────────────────────────────────────────────

def company_research(company_name: str, sector: str = "") -> dict:
    """
    Full company research workflow.
    Returns dict with brief (markdown), file_path, signals_found, sources.
    """

    # STEP 1: CONTEXT
    thesis = load_context("thesis")

    # STEP 2: INPUT — live signals
    query        = f"{company_name} {sector} startup funding news 2024 2025"
    signals      = exa_search(query)
    signals_text = _format_signals(signals)

    # STEP 3: PROCESS
    system = f"""You are an investment analyst assistant for a VC and angel investor.
Produce a clean, honest, structured company brief.

Investor thesis and focus:
{thesis if thesis else "Focus on early-stage European tech and FinTech companies."}

Rules:
- Be specific, not vague
- If data is missing, say so explicitly rather than guessing
- red_flags must never be empty — every company has risks worth flagging
- Keep each field concise (2-4 sentences max)
- thesis_fit must be exactly one of: Strong, Partial, Weak"""

    user = f"""Research this company: {company_name}
{f"Sector context: {sector}" if sector else ""}

Live signals:
{signals_text}

Return structured JSON for the brief now."""

    brief_data = call_claude_structured(system, user, schema=CompanyBrief, max_tokens=1500)

    # STEP 4: OUTPUT — render to markdown and save
    date_str = datetime.now().strftime("%d %B %Y")
    md = f"""# {company_name} — Research Brief
**Date:** {date_str}
**Sector:** {brief_data.sector}
**Stage:** {brief_data.stage}
**Geography:** {brief_data.geography}

## What They Do
{brief_data.what_they_do}

## Funding History
{brief_data.funding_history}

## Team
{brief_data.team}

## Traction Signals
{brief_data.traction_signals}

## Red Flags
{brief_data.red_flags}

## Thesis Fit — {brief_data.thesis_fit}
{brief_data.thesis_fit_reason}

## Recommended Next Step
{brief_data.recommended_next_step}

---
*Brief generated by AI-OS · {date_str}*"""

    safe_name = company_name.lower().replace(" ", "_").replace("/", "-")
    filename  = f"{safe_name}_{datetime.now().strftime('%Y%m%d')}.md"
    file_path = save_output(md, "companies", filename)

    return {
        "company":       company_name,
        "brief":         md,
        "file_path":     str(file_path),
        "signals_found": len(signals),
        "sources":       [r["url"] for r in signals if r.get("url")],
    }
